# Generated by Django 5.0.1 on 2024-03-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalinfo',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patientinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
