# Generated by Django 5.0.1 on 2024-03-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_file', '0003_alter_patientinfo_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalinfo',
            name='certificates',
            field=models.ImageField(upload_to='certificates/'),
        ),
    ]
