# Generated by Django 5.0.1 on 2024-03-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_file', '0004_alter_hospitalinfo_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalinfo',
            name='speciality',
            field=models.CharField(max_length=200),
        ),
    ]
