# Generated by Django 5.0.1 on 2024-03-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_file', '0005_alter_hospitalinfo_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalinfo',
            name='hospital_photo',
        ),
    ]
