# Generated by Django 5.0.1 on 2024-03-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_file', '0006_remove_hospitalinfo_hospital_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
